name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Debug Composer Dependencies
      run: composer show --tree
    - name: Check PHP Version
      run: php -v
    - name: Check Installed Extensions
      run: php -m
    - name: Copy .env
      run: cp .env.example .env
    - name: Generate application key
      run: php artisan key:generate
    - name: Set up database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Run migrations
      run: php artisan migrate --force
    - name: Run tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test